### ISSUE TITLE
drozer agent not working on Huawei mate 20 pro

### ISSUE THREAD

**Issue by nocomp** [FSecureLABS/drozer#368]
hi folks
first of all, thank you for this great tool, really appreciate it.
i tried to use it on my huawei, but impossible to launch it
in the console i get hundreds of 
IO Error Reseting connections
Attemptig to bind to port 31415

any idea how solve this?
thxx for yoru time

**Comment by mkaraoz** [comment]
I changed the port to 60000 and this solved the IO errors, but i still get the following error when I try to connect:

here was a problem connecting to the drozer Server.

Things to check:

 - is the drozer Server running?
 - have you set up appropriate adb port forwards?
 - have you specified the correct hostname and port with --server?
 - is the server protected with SSL (add an --ssl switch)?
 - is the agent protected with a password (add a --password switch)?

Debug Information:
[Errno 111] Connection refused

**Comment by nocomp** [comment]
I ve solved the issue by selling my phone and bought a xiaomi, and everything is ok. In a phone shop, i tried on several phones, all honor and huawei have the same issue.

**Comment by mkaraoz** [comment]
Since I am not allowed to sella company phone I found a work aroud. May help others:

Connect the phone and the computer to the same network.

On your computer type: `drozer server start`

Go to your phone and  click Settings -> New ENDPOINT-> Configure host IP.OF.YOUR.COMPUTER

Hit on button for the new endpoint. Switch back to your computer and run the following command:
`drozer console connect --server IP.OF.THE.COMPUTER`

Source: https://translate.google.com/translate?hl=tr&sl=auto&tl=en&u=https%3A%2F%2Fblog.csdn.net%2Fweixin_39304739%2Farticle%2Fdetails%2F97013897

**Comment by Yogehi** [comment]
`I ve solved the issue by selling my phone and bought a xiaomi`

lol
